trigger:
- dev

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm ci
    NODE_OPTIONS="--max-old-space-size=4096" npm run build
  displayName: 'Install npm dependencies and build'
  env:
    RESEND_API_KEY: $(RESEND_API_KEY)

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)'
    Contents: |
      .next/**
      public/**
      package.json
      package-lock.json
      node_modules/**
      next.config.js
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copy files to staging directory'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.ArtifactStagingDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/nextjs-artifact.zip'
    replaceExistingArchive: true
  displayName: 'Archive files into a .zip'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/nextjs-artifact.zip'
    ArtifactName: 'nextjs-artifact'
    publishLocation: 'Container'
  displayName: 'Publish Build Artifacts'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'native-portal-connection'
    appName: 'native-portal'
    package: '$(Build.ArtifactStagingDirectory)/nextjs-artifact.zip'
  displayName: 'Deploy to Azure App Service'
