trigger:
- dev

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'Install npm dependencies and build'

# Copy necessary files to staging directory
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)'
    Contents: |
      .next/**
      public/**
      package.json
      package-lock.json
      # Include any other files necessary for your app
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copy files to staging directory'

# Create a .zip file from the staged files
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.ArtifactStagingDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/nextjs-artifact.zip'
    replaceExistingArchive: true
  displayName: 'Archive files into a .zip'

# Publish the .zip as a build artifact
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/nextjs-artifact.zip'
    ArtifactName: 'nextjs-artifact'
    publishLocation: 'Container'
  displayName: 'Publish Build Artifacts'

# Deploy the .zip package to Azure Web App
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'native-portal-connection'  # Replace with your actual service connection name
    appName: 'native-portal'
    package: '$(Build.ArtifactStagingDirectory)/nextjs-artifact.zip'
    resourceGroupName: 'rg-nativecloud-web'
  displayName: 'Deploy to Azure App Service'
